# Generated by Django 5.1.3 on 2024-11-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_remove_question_option_a_remove_question_option_b_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_option',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='user',
        ),
        migrations.AddField(
            model_name='question',
            name='score_a',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='score_b',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='score_c',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='score_d',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='answer',
            field=models.CharField(max_length=1),
        ),
    ]
